pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "mcrl"
  dataset_name: "water_velocity"
  # qualifier: ""
  temporal: "1s"
  data_level: "b1" # If not applying QC this should be set to "a1"

dataset_definition:
  attributes:
    title: "Sequim Bay Inlet Current"
    description: "Velocity data from ADCP deployed on a lander in the inlet to Sequim Bay"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/tsdat/ingest-template
    location_meaning: "PNNL Marine and Coastal Research Laboratory, Sequim, WA"

  dimensions:
    time:
      length: unlimited
    time_b5:
      length: unlimited
    range:
      length: unlimited
    range_b5:
      length: unlimited
    dir:
      length: 4
    dirIMU:
      length: 3
    q:
      length: 4
    inst:
      length: 3
    earth:
      length: 3
    beam:
      length: 4
    inst*:
      length: 4

  variable_defaults:
    input:
      attrs:
        _FillValue: nan

  variables:
    time:
      input:
        name: time
      dims: [time]
      type: float
      attrs:
        long_name: Time (UTC) # automatically converts this without tz based on local computer
        units: "seconds since 1970-01-01T00:00:00"
        description: Timestamp for data generated by ADCP beams 1-4
    time_b5:
      input:
        name: time
      dims: [time_b5]
      type: float
      attrs:
        long_name: Time (UTC) # automatically converts this without tz based on local computer
        units: "seconds since 1970-01-01T00:00:00"
        description: Timestamp for data generated by "5th" ADCP beam
    range:
      input:
        name: range
      dims: [range]
      type: double
      attrs:
        description: Distance to the center of each depth bin
        units: m
    range_b5:
      input:
        name: range
      dims: [range_b5]
      type: double
      attrs:
        description: Distance to the center of each depth bin
        units: m
    dir:
      input:
        name: dir
      dims: [dir]
      type: str
      attrs:
        description: Coordinate axes given the reference frame (`ds.coord_sys``)
    dirIMU:
      input:
        name: dirIMU
      dims: [dirIMU]
      type: str
      attrs:
        description: Coordinate axes for IMU data
    beam:
      input:
        name: beam
      dims: [beam]
      type: int
      attrs:
        description: Beam coordinate axes
    inst*:
      input:
        name: inst*
      dims: [inst*]
      type: str
      attrs:
        description: Instrument mapping for beam coordinates
    inst:
      input:
        name: inst
      dims: [inst]
      type: str
      attrs:
        description: Instrument coordinate axes
    earth:
      input:
        name: earth
      dims: [earth]
      type: str
      attrs:
        description: Earth coordinate axes
    q:
      input:
        name: q
      dims: [q]
      type: str
      attrs:
        description: Quaternion coordinates

    velocity:
      input:
        name: vel
      dims: [dir, range, time]
      type: double
      attrs:
        description: Measured water velocity
        units: m/s
    velocity_b5:
      input:
        name: vel_b5
      dims: [range_b5, time_b5]
      type: double
      attrs:
        description: Along beam velocity measured by 5th beam
        units: m/s

    speed:
      input:
        name: U_mag
      dims: [range, time]
      type: double
      attrs:
        description: Horizontal velocity magnitude
        units: m/s
    speed_dir:
      input:
        name: U_dir
      dims: [range, time]
      type: double
      attrs:
        description: Horizontal velocity direction
        units: deg from North

    amplitude:
      input:
        name: amp
      dims: [dir, range, time]
      type: double
      attrs:
        description: Amplitude of acoustic signal backscatter, reference relative to instrument
        units: dB
    amplitude_b5:
      input:
        name: amp_b5
      dims: [range_b5, time_b5]
      type: double
      attrs:
        description: Amplitude of 5th beam acoustic signal backscatter, reference relative to instrument
        units: dB

    correlation:
      input:
        name: corr
      dims: [dir, range, time]
      type: double
      attrs:
        description: Broadband acoustic signal correlation as a measure of similarity
        units: "%"
    correlation_b5:
      input:
        name: corr_b5
      dims: [range_b5, time_b5]
      type: double
      attrs:
        description: 5th beam broadband acoustic signal correlation as a measure of similarity
        units: "%"

    depth:
      input:
        name: depth
      dims: [time]
      type: double
      attrs:
        description: Seafloor depth, calculated from temperature, salinity and pressure
        units: m
    water_density:
      input:
        name: water_density
      dims: [time]
      type: double
      attrs:
        description: Water density according to UNESCO 1981 equation of state
        units: kg/m^3

    heading:
      input:
        name: heading
      dims: [time]
      type: double
      attrs:
        units: deg
    pitch:
      input:
        name: pitch
      dims: [time]
      type: double
      attrs:
        units: deg
    roll:
      input:
        name: roll
      dims: [time]
      type: double
      attrs:
        units: deg
    quaternions:
      input:
        name: quaternion
      dims: [q, time]
      type: double
      attrs:
        description: IMU orientation
        units: ""
    quaternions_b5:
      input:
        name: quaternion_b5
      dims: [q, time]
      type: double
      attrs:
        description: IMU orientation during 5th beam measurement
        units: ""
    acceleration:
      input:
        name: accel
      dims: [dirIMU, time]
      type: double
      attrs:
        units: m/s^2
    angular_rotation:
      input:
        name: angrt
      dims: [dirIMU, time]
      type: double
      attrs:
        units: rad/s
    magnetometer:
      input:
        name: mag
      dims: [dirIMU, time]
      type: double
      attrs:
        units: uT
    acceleration_b5:
      input:
        name: accel_b5
      dims: [dirIMU, time]
      type: double
      attrs:
        units: m/s^2
    angular_rotation_b5:
      input:
        name: angrt_b5
      dims: [dirIMU, time]
      type: double
      attrs:
        units: rad/s
    magnetometer_b5:
      input:
        name: mag_b5
      dims: [dirIMU, time]
      type: double
      attrs:
        units: uT

    beam2inst_orientmat:
      input:
        name: beam2inst_orientmat
      dims: [beam, inst*]
      type: double
      attrs:
        description: Beam (1-4) to instrument (XYZ) orientation matrix
    earth2inst_orientmat:
      input:
        name: orientmat
      dims: [earth, inst, time]
      type: double
      attrs:
        description: Earth (ENU) to instrument (XYZ) orientation matrix

    speed_of_sound:
      input:
        name: c_sound
      dims: [time]
      type: double
      attrs:
        description: Speed of sound in water calculated in instrument as a funtion of user-specified salinity and measured temperature
        units: m/s
    pressure:
      input:
        name: pressure
      dims: [time]
      type: double
      attrs:
        description: Water pressure at ADCP
        units: dbar
    temperature:
      input:
        name: temp
      dims: [time]
      type: double
      attrs:
        description: Water temperature at ADCP
        units: deg C

    ensemble:
      input:
        name: ensemble
      dims: [time]
      type: int
      attrs:
        description: Ping count
    ensemble_b5:
      input:
        name: ensemble_b5
      dims: [time]
      type: int
      attrs:
        description: 5th beam ping count
    error:
      input:
        name: error
      dims: [time]
      type: int
      attrs:
        description: Instrument error code
    error_b5:
      input:
        name: error_b5
      dims: [time]
      type: int
      attrs:
        description: 5th beam instrument error code
    battery:
      input:
        name: batt
      dims: [time]
      type: double
      attrs:
        description: Battery voltage
        units: V

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - time

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [ensemble, ensemble_b5, battery, error, error_b5]
