storage:
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      lander:
        file_pattern: ".*_sea_spider.ad2cp"
        classname: ingest.current_mcrl.pipeline.filehandler.AdcpUpHandler
        parameters:
          depth: 0.6
          salinity: 31
          magn_declination: 15.8
          corr_threshold: 50

      vessel:
        file_pattern: ".*UTC.ad2cp"
        classname: ingest.current_mcrl.pipeline.filehandler.AdcpDownHandler
        parameters:
          depth: 0.6
          amp_threshold: 40
          magn_declination: 15.8
          corr_threshold: 50

    output:
      netcdf:
        file_extension: ".nc"
        # classname: tsdat.io.filehandlers.NetCdfHandler

        classname: tsdat.io.filehandlers.netcdf_handler.SplitNetCDFHandler
        parameters:
          write:
            time_interval: 1
            time_unit: "D"
