pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "clallam"
  dataset_name: "wave_buoy"
  qualifier: "gps"
  temporal: "400ms"
  data_level: "b1" # If not applying QC this should be set to "a1"

dataset_definition:
  attributes:
    title: "Spotter_Buoy"
    description: "GPS data taken with a Spotter buoy in Clallam Bay, WA over a month-long deployment in Aug-Sep 2020"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/tsdat/ingest-template
    location_meaning: "Clallam Bay"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: time
        converter:
          classname: "tsdat.utils.converters.TimestampTimeConverter"
          parameters:
            timezone: "US/Pacific"
            unit: "s"
      dims: [time]
      type: float
      attrs:
        long_name: Time (UTC) # automatically converts this without tz based on local computer
        standard_name: time
        units: "seconds since 1970-01-01T00:00:00"

    latitude: # Name of variable in the output file
      input:
        name: lat # Name of variable in the input file
      dims: [time]
      type: float # The data type, typically one of: `float`, `long`, `int`
      attrs:
        units: "deg N"
    longitude: # Name of variable in the output file
      input:
        name: lon # Name of variable in the input file
      dims: [time]
      type: float # The data type, typically one of: `float`, `long`, `int`
      attrs:
        units: "deg E"

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - time

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: []
