storage:
  # This section should not be modified unless there is a strong need. Please contact
  # the repository maintainers if you feel you need to use different settings here –
  # there may be another way to accomplish what you need.
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      # TODO – Developer: Update the FileHandler here as needed
      my_custom_format: # Solely used as a label. See the 'csv' input
        # filehandler below
        file_pattern: ".*" # The regex pattern used to match to an input file.
        # Note this will only be applied to files already
        # matched by a mapping in mapping.py, so .* is fine
        # unless you need to use multiple handlers within
        # those matched files.
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.CustomFileHandler

      wpr:
        file_pattern: ".wpr"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      vec:
        file_pattern: ".VEC"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      ad2cp:
        file_pattern: ".ad2cp"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      #000: # An unfortunate naming choice
      #  file_pattern: '.*.000'
      #  classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      PD0:
        file_pattern: ".PD0"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      enr:
        file_pattern: ".ENR"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler
      enx:
        file_pattern: ".ENX"
        classname: ingest.sequim_current_mcrl.pipeline.filehandler.DolfynFileHandler

    # The output section should not be modified unless there is a strong need. Please
    # contact the repository maintainers if you feel you need to write to a different
    # format.
    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler
