storage:
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      vessel:
        file_pattern: ".*_Desdemona.ad2cp"
        classname: ingest.current_vm_mcrl.pipeline.filehandler.AdcpDownHandler
        parameters:
          depth: 0.5
          amp_threshold: 40
          magn_declination: 15.8
          corr_threshold: 50

      netcdf:
        file_pattern: ".*.nc"
        classname: tsdat.io.filehandlers.NetCdfHandler

    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.netcdf_handler.SplitNetCDFHandler
        parameters:
          write:
            compression: True
            time_interval: 1
            time_unit: "D"
