storage:
  # This section should not be modified unless there is a strong need. Please contact
  # the repository maintainers if you feel you need to use different settings here –
  # there may be another way to accomplish what you need.
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      wpr:
        file_pattern: ".*.wpr"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      vec:
        file_pattern: ".*.VEC"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      ad2cp:
        file_pattern: ".*.ad2cp"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      #000: # An unfortunate naming choice
      #  file_pattern: '.*.000'
      #  classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      PD0:
        file_pattern: ".*.PD0"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      enr:
        file_pattern: ".*.ENR"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler
      enx:
        file_pattern: ".*.ENX"
        classname: ingest.current.pipeline.filehandler.DolfynFileHandler

    # The output section should not be modified unless there is a strong need. Please
    # contact the repository maintainers if you feel you need to write to a different
    # format.
    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler
